# serverless.yml

service: aws-s3-file-to-dynamo
app: s3-file-to-dynamo

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
      Resource:
        Fn::GetAtt:
          - cerealTable
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::GetAtt:
          - cerealBucket
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - Fn::GetAtt:
              - cerealBucket
              - Arn
            - "/*"

plugins:
  - serverless-s3-sync
  - invoke-lambda

custom:
  s3Sync:
    - bucketName: "cereal-bucket"
      localDir: "upload_files"

functions:
  updateDynamoDb:
    handler: handler.updateDynamoDb
    name: updateDynamoDb
    description: Extracts data from S3 and inserts data into DynamoDB
    memorySize: 512
    environment:
      bucket: ${self:resources.Resources.cerealBucket.Properties.BucketName}
      key: "shortCereals.json"
      table: ${self:resources.Resources.cerealTable.Properties.TableName}
      region: ${self:provider.region}

resources:
  Resources:
    cerealTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "cerealTable"
        AttributeDefinitions:
          -
            AttributeName: "cerealId"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "cerealId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
    cerealBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "cereal-bucket"

package:
  exclude:
    - README.md
    - node_modules
    - package-lock.json
    - package.json
    - upload_files/**
    - .serverless_plugins
