# serverless.yml

service: aws-s3-file-to-dynamo
app: s3-file-to-dynamo

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource:
        Fn::GetAtt:
          - cerealTable
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        Fn::GetAtt:
          - cerealBucket
          - Arn
    - Effect: "Allow"
      Action:
        - "s3:DeleteObject"
        - "s3:GetObject"
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - Fn::GetAtt:
              - cerealBucket
              - Arn
            - "/*"

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: "cereal-bucket"
      localDir: "upload_files"

functions:
  updateDynamoDb:
    handler: handler.updateDynamoDb
    name: updateDynamoDb
    descriptions: Extracts data from S3 and inserts data into DynamoDB

resources:
  Resources:
    cerealTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "cerealTable"
        AttributeDefinitions:
          -
            AttributeName: "cerealId"
            AttributeType: "N"
        KeySchema:
          -
            AttributeName: "cerealId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
    cerealBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "cereal-bucket"

package:
  exclude:
    - README.md
    - node_modules
    - package-lock.json
    - package.json
    - upload_files
