# serverless.yml

service: api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::ImportValue: madLibTemplatesArnExp

functions:
  getMadlib:
    handler: endpoints/getMadlib.getMadlib
    name: ${self:provider.stage}-getMadlib
    description: Performs item lookup based on ID
    memorySize: 512
    events:
      - http:
          path: /get-madlib/{ID}
          method: get
          cors: true
    environment:
      region: ${self:provider.region}
      table:
        Fn::ImportValue: madLibTemplatesNameExp
    package:
      include:
        - ../lib/response.js
