# serverless.yml

service: api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::ImportValue: madLibTemplatesArnExp

functions:
  getEndpoint:
    handler: endpoints/getItem.getEndpoint
    name: ${self:provider.stage}-getEndpoint
    description: Performs item lookup based on ID
    events:
      - http:
          path: /api/{ID}
          method: get
          cors: true
    environment:
      region: ${self:provider.region}
      table:
        Fn::ImportValue: madLibTemplatesNameExp

package:
  include:
    - ../lib/**
